export const drawerWidth = 280;

export const navItems = [
  { title: "마일리지 항목 관리", to: "/mileage/activity" },
  { title: "마일리지 참여 관리", to: "/mileage/participant" },
  { title: "마일리지 장학금 신청자 관리", to: "/scholarship/management" },
  { title: "마일리지 장학금 수혜자 조회", to: "/scholarship/lists" },
  { title: "학생 관리", to: "/student" },
  { title: "학부 관리", to: "/department" },
  { title: "전공 관리", to: "/major" },
  { title: "마일리지 카테고리 관리", to: "/category" },
  { title: "공지 관리", to: "/notice" },
  { title: "관리자 권한 관리", to: "/admin/management" },
  { title: "신청자", to: "/scholarship/FileManagerPage" },
];

export const mileageCategories = [
  "1. 전공 마일리지",
  "2. 산학 마일리지",
  "3. 비교과-전공활동",
  "4. 비교과-연구활동",
  "5. 비교과-특강참여",
  "6. 비교과-행사참여",
  "7. 비교과-학회활동",
  "8. 기타",
];

export const semesterList = [
  "2022-2",
  "2022-1",
  "2021-2",
  "2021-1",
  "2020-2",
  "2020-1",
];

export const departmentList = [
  "전산전자공학부",
  "국제어문학부",
  "경영경제학부",
  "법학부",
  "커뮤니케이션학부",
  "상담심리사회복지학부",
  "공간환경시스템공학부",
  "콘텐츠융합디자인공",
  "기계제어공학부",
  "ICT창업학부",
  "AI 융합 교육원",
  "창의융합교육원",
  "생명과학부",
];

export const major1List = [
  "-",
  "건설공학전공",
  "도시환경공학전공",
  "기계공학전공",
  "전자제어공학전공",
  "생명과학전공",
  "글로벌융합전공",
  "수학통계전공",
  "학생설계융합전공",
  "시각디자인전공",
  "제품디자인전공",
  "컴퓨터공학전공",
  "컴퓨터공학심화전공",
  "전자공학전공",
  "전자공학심화전공",
  "Information Technology",
  "ICT 융합전공",
  "AI Convergence & Entrepreneurship",
  "Global Entrepreneurship",
  "AI 융합",
  "데이터 사이언스 전공",
  "경영학전공",
  "경제학전공",
  "Global Management",
  "국제지역학전공",
  "영어전공",
  "한국법전공",
  "US & International Law",
  "상담심리학전공",
  "사회복지학전공",
  "공연영상학전공",
  "언론정보학전공",
  "글로벌융합전공",
  "학생설계융합전공",
  "글로벌한국학전공",
];

export const major2List = [
  "-",
  "건설공학전공",
  "도시환경공학전공",
  "기계공학전공",
  "전자제어공학전공",
  "생명과학전공",
  "글로벌융합전공",
  "수학통계전공",
  "학생설계융합전공",
  "시각디자인전공",
  "제품디자인전공",
  "컴퓨터공학전공",
  "컴퓨터공학심화전공",
  "전자공학전공",
  "전자공학심화전공",
  "Information Technology",
  "ICT 융합전공",
  "AI Convergence & Entrepreneurship",
  "Global Entrepreneurship",
  "AI 융합",
  "데이터 사이언스 전공",
  "경영학전공",
  "경제학전공",
  "Global Management",
  "국제지역학전공",
  "영어전공",
  "한국법전공",
  "US & International Law",
  "상담심리학전공",
  "사회복지학전공",
  "공연영상학전공",
  "언로정보학전공",
  "글로벌융합전공",
  "학생설계융합전공",
  "글로벌한국학전공",
];
